version: '3.8'
services:
  backend:
    container_name: espresso
    build:
      context: ./espresso/
      dockerfile: Dockerfile.dev
    volumes:
      - ./espresso/src:/code/api/src
      - /code/api/node_modules
      - ./.env:/code/api/.env
      - ./.env:/code/api/src/.env
      - ./espresso/logs:/code/api/logs  # Mounts the 'logs' directory from host to container.
    ports:
      - '8000:8000'
      - '9229:9229'
    command: ["npm", "run", "dev"]
    environment:
      - TZ=Asia/Kolkata 
    depends_on:
      - database
    networks:
      - 'matrix'
  database:
    container_name: database
    build:
      context: ./database/
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matrix
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - matrix

volumes:
  postgres_data:

networks:
  matrix:
    driver: bridge