FROM node:18-alpine

WORKDIR /code/api

COPY ./package.json ./package-lock.json ./

RUN npm cache clean --force

RUN npm install --legacy-peer-deps

COPY src/ ./src

#DEV
EXPOSE 8000 9229

CMD ["npm", "run", "dev"]
